### PR TITLE
Additional packages tex

### PR DESCRIPTION
**Pull request by jsuchome**
Backport of @thutterer work for installation of additional packages.

I'm not sure about the schema version. Isn't actually the master version wrong, so ``tex`` could continue with numbers after 20?

(requires https://github.com/crowbar/barclamp-crowbar/pull/1291)

### CODE REVIEW

**Comment by jsuchome** [comment]
@rsalevsky @tboerger you were commenting on the original PR, could you take a look here? Thanks.

**Comment by tboerger** [comment]
Nobody said that this needs to be backported. For backporting that we have to take the old versioning :(

**Comment by tboerger** [comment]
Beside that LGTM

**Comment by vuntz** [comment]
>  For backporting that we have to take the old versioning :(

@tboerger can you clarify? I'm not sure which versioning you're referring to, or which issue you think could happen. Is this the schema version?

**Comment by tboerger** [comment]
> @tboerger can you clarify? I'm not sure which versioning you're referring to, or which issue you think could happen. Is this the schema version?

Forget that, i thought that we raised the schema version to above 30 :)

**Comment by vuntz** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
Can you pickup #433 ?

**Comment by aplanas** [comment]
+1

**Pull request merged**
