### PR TITLE
[WIP] Initial pass at supporting more than just x86_64

### PR DESCRIPTION
**Pull request by vuntz**
Depends on:
* https://github.com/crowbar/crowbar/pull/2091
* https://github.com/crowbar/barclamp-crowbar/pull/1262
* https://github.com/SUSE-Cloud/suse-cloud-upgrade/pull/54
* https://github.com/cloudbase/adk-tools/pull/9
* [crowbar packaging change](http://paste.opensuse.org/view/raw/12452794)
* [barclamp-provisioner packaging change](http://paste.opensuse.org/view/raw/70497300)

### CODE REVIEW

**Comment by vuntz** [comment]
Still missing: be a bit more clever about default_platform being used when no target_platform is specified as it can't work for all architectures...

**Comment by tboerger** [comment]
LGTM

**Comment by rsalevsky** [comment]
@vuntz, this repository got merged into [crowbar-core](https://github.com/crowbar/crowbar-core).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by vuntz** [comment]
Closing as this will need to be rebased on top of https://github.com/crowbar/crowbar-core/pull/18

**Pull request closed without merging**
