### PR TITLE
Fix target_platform attribute not being set on some nodes (second try)

### PR DESCRIPTION
**Pull request by vuntz**
(marked as WIP because untested)

### CODE REVIEW

**Comment by vuntz** [comment]
Tested

**Comment by jsuchome** [comment]
It might be really needed for "hardware-installing" only, but wouldn't it be better to move it up,before even checking the state?

**Comment by vuntz** [comment]
@jsuchome I think the goal was to not do it unless a node is allocated, and hardware-installing is the first state that we reach after allocating a node. I guess an alternative is to check if the node is allocated and then do this.

**Comment by vuntz** [comment]
Clicked "comment" to fast: would you prefer me to use the alternative I mentioned above?

**Comment by jsuchome** [comment]
I do not really have strong opinion here, that was just something that came to mind first. I think the patch looks good (but I thought the same about previous one)

**Comment by vuntz** [comment]
Merging as there was no objection in two weeks, it fixes a P1 bug and this has been tested as package patch.

**Pull request merged**
