### PR TITLE
Rename Cloud-PTF repo to just PTF

### PR DESCRIPTION
**Pull request by tserong**
This moves the Cloud-PTF repo out of the optional cloud repo set, to a
new optional common repo set.  For discussion on how this came about, see:

  https://github.com/crowbar/crowbar/pull/2108

Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Comment by aspiers** [comment]
+1 but won't this need a corresponding change to mkcloud?

**Comment by tserong** [comment]
> +1 but won't this need a corresponding change to mkcloud?

Good point. How's https://github.com/SUSE-Cloud/automation/pull/419 look?

**Comment by aspiers** [comment]
Looks good to me, thanks!

**Comment by vuntz** [comment]
+1

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
