### PR TITLE
For large disks, we're gonna need to create BIOS boot partition

### PR DESCRIPTION
**Pull request by jsuchome**
backport of https://github.com/crowbar/crowbar-core/pull/30

### CODE REVIEW

**Comment by dguitarbite** [comment]
@jsuchome Just a suggestion to rephrase the commit message "Create bios_boot partition for disks bigger than 4TB size" ... although I do not see any checks for disk size. Rather "Create bios_boot partition to consider bigger RAID disks".

**Comment by vuntz** [comment]
Can't really say if that's correct or not, but nothing obviously wrong. So +0.5 from me because it fixes the issue according to the bug.

**Comment by dguitarbite** [comment]
@vuntz Its probably the best possible replacement for /boot partition since GRUB 2 onwards.

**Comment by jsuchome** [comment]
@dguitarbite I've merged the master version, do you thinnk you can give +1 here as well?

**Comment by dguitarbite** [comment]
+1 LGTM

@jsuchome Although I would suggest a small nitpick in your commit message, can you please add the reference to the other PR and mention it as backport?

**Comment by rsalevsky** [comment]
+1

**Comment by dguitarbite** [comment]
I am not sure if this will work with sle11 as it has grub 1 and bios_boot
partition may not work. Can you verify this once? It should work for sle12
though.

**Comment by jsuchome** [comment]
For SLE12 it works, but you're right, I should test it also for Cloud5 and SLE11 nodes

**Comment by jsuchome** [comment]
@dguitarbite just tested with SLE11 nodes of Clood5: works fine.

**Comment by dguitarbite** [comment]
Awesome, in that case I'll update my patch too. In this case I believe we
do not need a /boot partition.

**Pull request merged**
