### PR TITLE
Don't install ruby 1.8 anymore on the nodes

### PR DESCRIPTION
**Pull request by dirkmueller**
We don't need it anymore.

### CODE REVIEW

**Comment by dirkmueller** [comment]
it has the slight downside that the installer comes up in text mode now.. not sure how to resolve that.

**Comment by tboerger** [comment]
LGTM

**Comment by vuntz** [comment]
I'm wondering if it makes a big difference?

**Comment by dirkmueller** [comment]
@vuntz it avoids that something accidentally refers to /usr/bin/ruby and we git strange bugs due to that. it also removes a few MB of disk usage, but I guess you're not worried about that ;)

**Comment by tboerger** [comment]
We have puppet and facter installed somewhere?

**Comment by toabctl** [comment]
+1 (but not tested)

**Comment by dirkmueller** [comment]
@tboerger puppet is installed on all machines by the base pattern. thats why I need to add the override in order to be able to not install ruby 1.8

**Comment by tboerger** [comment]
Ok :+1:

**Comment by rsalevsky** [comment]
+1

**Comment by aspiers** [comment]
It would be nice if the commit message briefly explained why it is no longer needed.

**Comment by rsalevsky** [comment]
@dirkmueller, this repository got merged into [crowbar-core](https://github.com/crowbar/crowbar-core).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by dirkmueller** [comment]
don't care about it anymore

**Pull request closed without merging**
