### PR TITLE
add some support for SLES-11-SP4

### PR DESCRIPTION
**Pull request by bmwiedemann**
This is mostly copying what we did for SP3

code is slightly tested (I installed my NUC with it by mounting the SP4-GM DVD onto the suse-11.3 install dir).

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Code-wise, +1. But before merging: I'm wondering if we should also have a PR for install-suse-cloud at the same time (since we usually do the two changes together).

**Comment by tboerger** [comment]
> Code-wise, +1. But before merging: I'm wondering if we should also have a PR for install-suse-cloud at the same time (since we usually do the two changes together).

It makes sense to integrate it into install-chef-suse, but anyway it doesnt block us from merging this.

**Comment by bmwiedemann** [comment]
I also think that the install-chef-suse change is independent of this one. Maybe it would require this change but not the other way round.

**Pull request merged**
