### PR TITLE
Renew DHCP lease after hardware-installing transtion

### PR DESCRIPTION
**Pull request by vuntz**
During the "hardware-installing" transition a new admin IP Address (from the
"host" ranges) gets allocated to the node. Force a DHCP renewal to change to
the new IP Address directly after the transition. This avoids having the IP
Address changed at a later (unpredictable) time during the remainder of the
sledgehammer phase.

Backport of https://github.com/crowbar/crowbar-core/pull/126

### CODE REVIEW

**Comment by jsuchome** [comment]
I thought we haven't moved IP allocation to hardware-installing in tex... oh, yes we did

**Comment by vuntz** [comment]
Oh, right, sorry.

**Comment by vuntz** [comment]
Actually, isn't that what we did in https://github.com/crowbar/barclamp-deployer/pull/253/files ?

**Comment by jsuchome** [comment]
@vuntz yes, we did, sorry, I updated my first comment after a minute...

**Comment by tboerger** [comment]
Makes sense :+1:

**Comment by vuntz** [comment]
For the record: this is missing a +1 (or objections) :-)

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
