### PR TITLE
Adopting control scripts for SLE12 based sleshammer image

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by dirkmueller** [comment]
after milestone 2...

**Comment by mjura** [comment]
Milestone 2 was released, let's move on with code-reviewing

**Comment by rsalevsky** [comment]
@mjura, this repository got merged into [crowbar-core](https://github.com/crowbar/crowbar-core).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by mjura** [comment]
Was moved to https://github.com/crowbar/crowbar-core/pull/6

**Comment by mjura** [comment]
Close this PR

**Pull request closed without merging**
