### PR TITLE
Minor cleanups to provisioner cookbooks + tentative use of grub for UEFI net boot on SLE12

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by rsalevsky** [comment]
@vuntz Is this PR tested?

**Comment by vuntz** [comment]
@rsalevsky yes, I ran the cookbook on a SLE12 node and that was working fine. What's not tested is full testing, but that's a bit too difficult without having the admin server running on SLE12 first.

**Comment by rsalevsky** [comment]
I'm fine with testing it finally when we have the admin node on SLE12. :+1:

**Pull request merged**
